// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import {ZKSettlement, IGroth16Verifier} from "../src/ZKSettlement.sol";

/// @title MockVerifier
/// @notice A mock Groth16 verifier that always returns true (for testing).
///         The real verifier is auto-generated by snarkjs from the circuit.
contract MockVerifier is IGroth16Verifier {
    bool public shouldPass = true;

    function setResult(bool _pass) external {
        shouldPass = _pass;
    }

    function verifyProof(
        uint256[2] calldata,
        uint256[2][2] calldata,
        uint256[2] calldata,
        uint256[7] calldata
    ) external view override returns (bool) {
        return shouldPass;
    }
}

/// @title ZKSettlementTest
/// @notice Tests for the ZKSettlement contract.
contract ZKSettlementTest is Test {
    ZKSettlement public zk;
    MockVerifier public mockVerifier;

    address public client   = makeAddr("client");
    address public entryOp  = makeAddr("entryOp");
    address public relayOp  = makeAddr("relayOp");
    address public exitOp   = makeAddr("exitOp");
    address public refundTo = makeAddr("refundTo");

    function setUp() public {
        mockVerifier = new MockVerifier();
        zk = new ZKSettlement(address(mockVerifier));

        vm.deal(client, 10 ether);

        // Set a dummy registry root.
        zk.updateRegistryRoot(12345);
    }

    // ── Helpers ──────────────────────────────────────────────────

    function _pubSignals(uint256 totalPayment) internal view returns (uint256[7] memory) {
        return [
            uint256(zk.DOMAIN_SEPARATOR()),  // domainSeparator
            totalPayment,                     // totalPayment
            uint256(1),                       // entryCommitment (dummy)
            uint256(2),                       // relayCommitment (dummy)
            uint256(3),                       // exitCommitment (dummy)
            uint256(4),                       // refundCommitment (dummy)
            uint256(12345)                    // registryRoot
        ];
    }

    function _dummyProof()
        internal
        pure
        returns (
            uint256[2] memory a,
            uint256[2][2] memory b,
            uint256[2] memory c
        )
    {
        // Dummy proof values — MockVerifier always passes.
        a = [uint256(0), uint256(0)];
        b = [[uint256(0), uint256(0)], [uint256(0), uint256(0)]];
        c = [uint256(0), uint256(0)];
    }

    // ── Deposit tests ────────────────────────────────────────────

    function test_deposit() public {
        bytes32 depositId = keccak256("deposit-1");

        vm.prank(client);
        zk.deposit{value: 0.01 ether}(depositId);

        assertEq(zk.deposits(depositId), 0.01 ether);
    }

    function test_deposit_too_low() public {
        vm.prank(client);
        vm.expectRevert("ZKSettlement: deposit too low");
        zk.deposit{value: 0.0001 ether}(keccak256("low"));
    }

    function test_deposit_duplicate() public {
        bytes32 depositId = keccak256("dup");

        vm.prank(client);
        zk.deposit{value: 0.01 ether}(depositId);

        vm.prank(client);
        vm.expectRevert("ZKSettlement: duplicate deposit");
        zk.deposit{value: 0.01 ether}(depositId);
    }

    // ── Settlement tests ─────────────────────────────────────────

    function test_settle_with_valid_proof() public {
        bytes32 depositId = keccak256("session-zk-1");
        bytes32 nullifier = keccak256("null-1");

        vm.prank(client);
        zk.deposit{value: 1 ether}(depositId);

        uint256 totalPayment = 1000; // 1000 wei
        uint256[7] memory pub = _pubSignals(totalPayment);
        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c) = _dummyProof();

        uint256 entryBefore = entryOp.balance;
        uint256 relayBefore = relayOp.balance;
        uint256 exitBefore  = exitOp.balance;
        uint256 refundBefore = refundTo.balance;

        zk.settleWithProof(
            a, b, c, pub,
            nullifier, depositId,
            payable(entryOp), payable(relayOp), payable(exitOp), payable(refundTo)
        );

        // 25/25/50 split of 1000 wei
        assertEq(entryOp.balance - entryBefore, 250);
        assertEq(relayOp.balance - relayBefore, 250);
        assertEq(exitOp.balance - exitBefore, 500);

        // Refund = 1 ether - 1000 wei
        assertEq(refundTo.balance - refundBefore, 1 ether - 1000);

        // Deposit cleared
        assertEq(zk.deposits(depositId), 0);

        // Nullifier used
        assertTrue(zk.nullifiers(nullifier));
    }

    function test_double_settle_reverts() public {
        bytes32 depositId = keccak256("session-ds");
        bytes32 nullifier = keccak256("null-ds");

        vm.prank(client);
        zk.deposit{value: 1 ether}(depositId);

        uint256[7] memory pub = _pubSignals(100);
        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c) = _dummyProof();

        zk.settleWithProof(
            a, b, c, pub,
            nullifier, depositId,
            payable(entryOp), payable(relayOp), payable(exitOp), payable(refundTo)
        );

        // Same nullifier → revert
        vm.expectRevert("ZKSettlement: already settled");
        zk.settleWithProof(
            a, b, c, pub,
            nullifier, depositId,
            payable(entryOp), payable(relayOp), payable(exitOp), payable(refundTo)
        );
    }

    function test_invalid_proof_reverts() public {
        bytes32 depositId = keccak256("session-inv");
        bytes32 nullifier = keccak256("null-inv");

        vm.prank(client);
        zk.deposit{value: 1 ether}(depositId);

        // Make verifier reject.
        mockVerifier.setResult(false);

        uint256[7] memory pub = _pubSignals(100);
        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c) = _dummyProof();

        vm.expectRevert("ZKSettlement: invalid proof");
        zk.settleWithProof(
            a, b, c, pub,
            nullifier, depositId,
            payable(entryOp), payable(relayOp), payable(exitOp), payable(refundTo)
        );
    }

    function test_wrong_domain_reverts() public {
        bytes32 depositId = keccak256("session-wd");

        vm.prank(client);
        zk.deposit{value: 1 ether}(depositId);

        uint256[7] memory pub = _pubSignals(100);
        pub[0] = 99999; // Wrong domain separator

        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c) = _dummyProof();

        vm.expectRevert("ZKSettlement: wrong domain");
        zk.settleWithProof(
            a, b, c, pub,
            keccak256("null-wd"), depositId,
            payable(entryOp), payable(relayOp), payable(exitOp), payable(refundTo)
        );
    }

    function test_stale_registry_root_reverts() public {
        bytes32 depositId = keccak256("session-sr");

        vm.prank(client);
        zk.deposit{value: 1 ether}(depositId);

        uint256[7] memory pub = _pubSignals(100);
        pub[6] = 99999; // Wrong registry root

        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c) = _dummyProof();

        vm.expectRevert("ZKSettlement: stale registry root");
        zk.settleWithProof(
            a, b, c, pub,
            keccak256("null-sr"), depositId,
            payable(entryOp), payable(relayOp), payable(exitOp), payable(refundTo)
        );
    }

    function test_payment_exceeds_deposit_reverts() public {
        bytes32 depositId = keccak256("session-pe");

        vm.prank(client);
        zk.deposit{value: 0.001 ether}(depositId);

        // Try to claim more than deposited.
        uint256[7] memory pub = _pubSignals(2 ether);
        (uint256[2] memory a, uint256[2][2] memory b, uint256[2] memory c) = _dummyProof();

        vm.expectRevert("ZKSettlement: payment exceeds deposit");
        zk.settleWithProof(
            a, b, c, pub,
            keccak256("null-pe"), depositId,
            payable(entryOp), payable(relayOp), payable(exitOp), payable(refundTo)
        );
    }

    // ── Admin tests ──────────────────────────────────────────────

    function test_update_registry_root() public {
        zk.updateRegistryRoot(67890);
        assertEq(zk.registryRoot(), 67890);
    }

    function test_update_registry_root_unauthorized() public {
        vm.prank(client);
        vm.expectRevert("ZKSettlement: not owner");
        zk.updateRegistryRoot(99999);
    }
}
