// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title TestKeys
/// @notice Pre-computed secp256k1 public keys for test private keys.
///         Generated by: node scripts/gen-test-keys.js
///         Each key is 64 bytes (x[32] || y[32]), no 0x04 prefix.
library TestKeys {
    /// secp256k1 pubkey for private key 0xA001
    function entry_key() internal pure returns (bytes memory) {
        return hex"c493d860b9a2db32479513a711462c910ace80e11289642cf507cbc1824df1ea01f4cf358efe9152102aae4ca3c888ea229deeb4c7a7364e4ae32705e94e16f1";
    }

    /// secp256k1 pubkey for private key 0xA002
    function relay_key() internal pure returns (bytes memory) {
        return hex"d162dcd258847660792cbcdeecaea49a5f6003ea4441384e01a3d29aea505f5db7e2904693b9af2e3b0f799f531548dfb96f7a548b94907c20f65a85086f8dba";
    }

    /// secp256k1 pubkey for private key 0xA003
    function exit_key() internal pure returns (bytes memory) {
        return hex"2306264321360d2274055b9bcfa4125f3cda125159e63d8573e5abe8d56ac2aa0bd2692d089ce765c02647882211e0331b030dfcad6f4b68a0692dd4846bda4b";
    }

    /// secp256k1 pubkey for private key 0xB001
    function client_key() internal pure returns (bytes memory) {
        return hex"9305675b6901e48b0bc3a4316fff2fa145b4d161431e22fe62ad8b3b2dc46ab327412b666d5963fdb8a868b4b72fdf75f7fe462bac6690fe04b554be606cafe8";
    }

    /// secp256k1 pubkey for private key 0xA101
    function node_key() internal pure returns (bytes memory) {
        return hex"7302d569a551bf21cfb2ccdf787155a3d40fb0108929e86f733d2ea36aea2e9b71f75fca2f3016613652bba4f534dd60d0d7b4720963385871c97e41d31398f5";
    }

    /// secp256k1 pubkey for private key 0xC0DE
    function chall_key() internal pure returns (bytes memory) {
        return hex"7231d7178e94bbd00b0d8098bf1c1e84f829930eaa8df138e5785af78300a655b5224946344e654654c23532fc0917e20ba8b6a0351f5744faf075a7fbe4a218";
    }

    /// secp256k1 pubkey for private key 0xDEAD1
    function operator_key() internal pure returns (bytes memory) {
        return hex"c44cbde121a541eeaa3f0875125e5c4b4b8736eb38d06d5f3ac040820ee91e73446902f9d15225fefa7509aaa7589b3ac749349cfe3b31fedea56deb7250cf61";
    }

}
